version: "3"

services:
  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
    volumes:
      - .vols/mongo:/data/db
  elastic:
    build: data/elastic
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
  data:
    build: data
    links:
      - "mongo"
      - "elastic"
  keycloak:
    image: jboss/keycloak
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/stabilty-realm.json
      - DB_VENDOR=h2
    volumes:
      - ./config/stabilty-realm.json:/tmp/stabilty-realm.json
volumes:
  mongo-data:
