version: "3"

services:
  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  data:
    build: data
    links:
      - "mongo"
  keycloak:
    image: jboss/keycloak
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/stabilty-realm.json
    volumes:
      - ./config/stabilty-realm.json:/tmp/stabilty-realm.json
volumes:
  mongo-data:
