version: "3"

services:
  app:
    image: node:10
    links:
      - "mongo"
      - "keycloak"
    ports:
      - "3000:3000"
  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
  data:
    build: data/randomuser
    links:
      - "mongo"
  keycloak:
    image: jboss/keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin

